part_name: 65820W030P
planarize:
  left_offset: 0.0
  right_offset: 0.0
  top_offset: 350.0
  bottom_offset: 350.0
homography_adjustment:
  camera_1:
    x_offset: 0.0
    y_offset: 0.0
    rotation_deg: 0.0
  camera_2:
    x_offset: 0.0
    y_offset: 0.0
    rotation_deg: 0.0
  camera_3:
    x_offset: 0.0
    y_offset: 0.0
    rotation_deg: 0.0
  camera_4:
    x_offset: 0.0
    y_offset: 0.0
    rotation_deg: 0.0
  camera_5:
    x_offset: 0.0
    y_offset: 0.0
    rotation_deg: 0.0